.TH TOMATOC 1 tomatoc\-VERSION
.SH NAME
tomatoc \- a control script for tomato pomodoro timer
.SH SYNOPSIS
.B tomato
.RB [ \-s ]
.RB [ \-d ]
.RB [ \-t ]
.RB [ \-k ]
.SH DESCRIPTION
.B tomatoc
is a control script for the tomato pomodoro timer
.SH OPTIONS
.TP
.BI s " " [\-s " " | " " \-\-start\]
Starts a new pomodoro timer

.TP
.BI d " " [\-d " " | " " \-\-display\]
Display status (paused/resumed) and remaining time

.TP
.BI t " " [\-t " " | " " \-\-toggle\]
Toggles between paused and resumed

.TP
.BI k " " [\-k " " | " " \-\-kill\]
Stops the complete pomodoro-session
